//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CmsAllianceModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CAEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CAEntities object using the connection string found in the 'CAEntities' section of the application configuration file.
        /// </summary>
        public CAEntities() : base("name=CAEntities", "CAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CAEntities object.
        /// </summary>
        public CAEntities(string connectionString) : base(connectionString, "CAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CAEntities object.
        /// </summary>
        public CAEntities(EntityConnection connection) : base(connection, "CAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vote> votes
        {
            get
            {
                if ((_votes == null))
                {
                    _votes = base.CreateObjectSet<vote>("votes");
                }
                return _votes;
            }
        }
        private ObjectSet<vote> _votes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the votes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovotes(vote vote)
        {
            base.AddObject("votes", vote);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmsAllianceModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="created">Initial value of the created property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="firstname">Initial value of the firstname property.</param>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="lastupdated">Initial value of the lastupdated property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="public_viewable">Initial value of the public_viewable property.</param>
        public static user Createuser(global::System.DateTime created, global::System.String email, global::System.String firstname, global::System.Int32 id, global::System.String lastname, global::System.DateTimeOffset lastupdated, global::System.String password, global::System.Boolean public_viewable)
        {
            user user = new user();
            user.created = created;
            user.email = email;
            user.firstname = firstname;
            user.id = id;
            user.lastname = lastname;
            user.lastupdated = lastupdated;
            user.password = password;
            user.public_viewable = public_viewable;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> approved
        {
            get
            {
                return _approved;
            }
            set
            {
                OnapprovedChanging(value);
                ReportPropertyChanging("approved");
                _approved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("approved");
                OnapprovedChanged();
            }
        }
        private Nullable<global::System.DateTime> _approved;
        partial void OnapprovedChanging(Nullable<global::System.DateTime> value);
        partial void OnapprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String company_name
        {
            get
            {
                return _company_name;
            }
            set
            {
                Oncompany_nameChanging(value);
                ReportPropertyChanging("company_name");
                _company_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("company_name");
                Oncompany_nameChanged();
            }
        }
        private global::System.String _company_name;
        partial void Oncompany_nameChanging(global::System.String value);
        partial void Oncompany_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> company_size
        {
            get
            {
                return _company_size;
            }
            set
            {
                Oncompany_sizeChanging(value);
                ReportPropertyChanging("company_size");
                _company_size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("company_size");
                Oncompany_sizeChanged();
            }
        }
        private Nullable<global::System.Int32> _company_size;
        partial void Oncompany_sizeChanging(Nullable<global::System.Int32> value);
        partial void Oncompany_sizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String company_website
        {
            get
            {
                return _company_website;
            }
            set
            {
                Oncompany_websiteChanging(value);
                ReportPropertyChanging("company_website");
                _company_website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("company_website");
                Oncompany_websiteChanged();
            }
        }
        private global::System.String _company_website;
        partial void Oncompany_websiteChanging(global::System.String value);
        partial void Oncompany_websiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email_confirmation_code
        {
            get
            {
                return _email_confirmation_code;
            }
            set
            {
                Onemail_confirmation_codeChanging(value);
                ReportPropertyChanging("email_confirmation_code");
                _email_confirmation_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email_confirmation_code");
                Onemail_confirmation_codeChanged();
            }
        }
        private global::System.String _email_confirmation_code;
        partial void Onemail_confirmation_codeChanging(global::System.String value);
        partial void Onemail_confirmation_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> email_confirmed
        {
            get
            {
                return _email_confirmed;
            }
            set
            {
                Onemail_confirmedChanging(value);
                ReportPropertyChanging("email_confirmed");
                _email_confirmed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("email_confirmed");
                Onemail_confirmedChanged();
            }
        }
        private Nullable<global::System.DateTime> _email_confirmed;
        partial void Onemail_confirmedChanging(Nullable<global::System.DateTime> value);
        partial void Onemail_confirmedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastlogin
        {
            get
            {
                return _lastlogin;
            }
            set
            {
                OnlastloginChanging(value);
                ReportPropertyChanging("lastlogin");
                _lastlogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastlogin");
                OnlastloginChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastlogin;
        partial void OnlastloginChanging(Nullable<global::System.DateTime> value);
        partial void OnlastloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset lastupdated
        {
            get
            {
                return _lastupdated;
            }
            set
            {
                OnlastupdatedChanging(value);
                ReportPropertyChanging("lastupdated");
                _lastupdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastupdated");
                OnlastupdatedChanged();
            }
        }
        private global::System.DateTimeOffset _lastupdated;
        partial void OnlastupdatedChanging(global::System.DateTimeOffset value);
        partial void OnlastupdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean public_viewable
        {
            get
            {
                return _public_viewable;
            }
            set
            {
                Onpublic_viewableChanging(value);
                ReportPropertyChanging("public_viewable");
                _public_viewable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("public_viewable");
                Onpublic_viewableChanged();
            }
        }
        private global::System.Boolean _public_viewable;
        partial void Onpublic_viewableChanging(global::System.Boolean value);
        partial void Onpublic_viewableChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmsAllianceModel", Name="vote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vote : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vote object.
        /// </summary>
        /// <param name="answer">Initial value of the answer property.</param>
        /// <param name="created">Initial value of the created property.</param>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="lastupdated">Initial value of the lastupdated property.</param>
        /// <param name="votee">Initial value of the votee property.</param>
        /// <param name="voter">Initial value of the voter property.</param>
        public static vote Createvote(global::System.Boolean answer, global::System.DateTime created, global::System.Int32 id, global::System.DateTimeOffset lastupdated, global::System.Int32 votee, global::System.Int32 voter)
        {
            vote vote = new vote();
            vote.answer = answer;
            vote.created = created;
            vote.id = id;
            vote.lastupdated = lastupdated;
            vote.votee = votee;
            vote.voter = voter;
            return vote;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean answer
        {
            get
            {
                return _answer;
            }
            set
            {
                OnanswerChanging(value);
                ReportPropertyChanging("answer");
                _answer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("answer");
                OnanswerChanged();
            }
        }
        private global::System.Boolean _answer;
        partial void OnanswerChanging(global::System.Boolean value);
        partial void OnanswerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset lastupdated
        {
            get
            {
                return _lastupdated;
            }
            set
            {
                OnlastupdatedChanging(value);
                ReportPropertyChanging("lastupdated");
                _lastupdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastupdated");
                OnlastupdatedChanged();
            }
        }
        private global::System.DateTimeOffset _lastupdated;
        partial void OnlastupdatedChanging(global::System.DateTimeOffset value);
        partial void OnlastupdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 votee
        {
            get
            {
                return _votee;
            }
            set
            {
                OnvoteeChanging(value);
                ReportPropertyChanging("votee");
                _votee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("votee");
                OnvoteeChanged();
            }
        }
        private global::System.Int32 _votee;
        partial void OnvoteeChanging(global::System.Int32 value);
        partial void OnvoteeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 voter
        {
            get
            {
                return _voter;
            }
            set
            {
                OnvoterChanging(value);
                ReportPropertyChanging("voter");
                _voter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("voter");
                OnvoterChanged();
            }
        }
        private global::System.Int32 _voter;
        partial void OnvoterChanging(global::System.Int32 value);
        partial void OnvoterChanged();

        #endregion
    
    }

    #endregion
    
}
